
# html lang
language: zh-Hans

# main menu navigation
menu:
  home: /
  archives: /archives
  tags: /tags
  #categories: /categories
  search: /search
  about: https://github.com/ToBeTree
  rss: /atom.xml

sitemap:
  path: sitemap.xml

disqus_shortname: tobetree

google_analytics: tobetree
baidu_analytics: FuckUBaidu

# Custom
## configure search page
search:
  path: search.xml
  field: post
  
# Miscelaneous
# favicon: /logo.png

# stylesheets loaded in the <head>
stylesheets:
# - /css/normalize.css
- //cdn.bootcss.com/pure/1.0.0/pure-min.css
- /css/xoxo.css

# scripts loaded in the end of the body
scripts:
#- //cdn.bootcss.com/zepto/1.2.0/zepto.min.js
#- /js/xoxo.js

# switch
show_excerpt: true
show_date: true
#footer
index_page: https://tobetree.github.io
main_site: https://github.com/ToBeTree
github: https://github.com/ToBeTree
